### PR TITLE
CommonJS without default

### PR DESCRIPTION
**Pull request by zertosh**
This is some trickery to support both ES module with a default and CommonJS without a default. Not only does this approach work with the actual require/import call, but it's fully flow complaint.

### CODE REVIEW

**Comment by zertosh** [comment]
Wdyt @yungsters and @kassens?

**Comment by yungsters** [comment]
I’ve been thinking about this all day! I’m so glad you came up with a working solution. This looks good to me. Thanks!

**Comment by yungsters** [comment]
Can you publish this either as a new version or as an alpha? I'd like to test it with my current stack.

**Comment by zertosh** [comment]
@yungsters, published this as `nullthrows@1.1.0` under the `next` tag. If it works out, then I'll publish it as `latest`.

**Pull request merged**
